image: yosssi/go:1.2
env:
  - GOPATH=/var/cache/drone
script:
  - export GOPATH=/var/cache/drone
  - PATH=$PATH:$GOPATH/bin
  - apt-get install -y mercurial
  - go get github.com/yosssi/gohtml
  - go test --cover ./...
git:
  depth: 1
notify:
  email:
    recipients:
      - yoshida.keiji.84@gmail.com

